### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by mrmarktyy** [xfgryujk/pixiv-to-weibo#1]
大佬你好， 我是从“微博登录和session恢复过程”一文追到这里的。我也刚好在研究如何恢复微博24小时过期的cookie。 

通过你的代码，我尝试自己尝试了一下，结果不是很成功。注：我不会python，只能大概看着你的代码猜测逻辑，然后用NODE进行实现。不知大佬是否方便，帮忙看下我的问题出在什么地方。
先谢谢了！

**Comment by mrmarktyy** [comment]
我在请求这个的时候 `https://passport.weibo.com/visitor/visitor?a=restore&cb=restore_back&from=weibo`  (Referer我用值的是https://passport.weibo.com/visitor/visitor?a=enter)
总是得到如下的回复

```
window.restore_back && restore_back({"retcode":50111250,"msg":"SUB Cookie \u4e0d\u5408\u6cd5","data":{"errline":480}})
```

其中msg是`SUB Cookie 不合法`

**Comment by xfgryujk** [comment]
我猜那个cookie没有带上，看你用的HTTP客户端怎么加cookie了，如果是cookie没有设置可以参考我博客里的解决方法

**Comment by mrmarktyy** [comment]
谢谢回复。
我是用HTTP库手动在每个请求的时候手动在header里加上cookie字段的。

我的操作流程现在是这样，

第一步是
`GET https://passport.weibo.com/visitor/visitor?a=enter`  完整请求大概如下图
![image](https://user-images.githubusercontent.com/1808651/59759761-20a64380-92d4-11e9-84f5-477423fc34bb.png)

然后得到回复大致是 reponse的body是Sina Visitor System 页面的HTML
response headers如下
![image](https://user-images.githubusercontent.com/1808651/59759920-7549be80-92d4-11e9-9dd2-c22e6b874b42.png)

没看出来headers里有什么要调整的。

然后第二步是
`GET https://passport.weibo.com/visitor/visitor?a=restore&cb=restore_back&from=weibo&_rand=0.9447518682493958`
其中Referer设置成上个请求的URL，即`https://passport.weibo.com/visitor/visitor?a=enter` （其他headers的设置同上）

于是这个请求的回复我就得到了这个"SUB Cookie 不合法"

![image](https://user-images.githubusercontent.com/1808651/59760065-c5288580-92d4-11e9-8199-58dfca126576.png)


麻烦帮忙看下这个流程有没有问题。谢谢！

**Comment by xfgryujk** [comment]
首先一般不会跳转到`https://passport.weibo.com/visitor/visitor`这个页面，这是我手动删几个cookie才会跳转到的，一般登录就是访问`login.sina.com.cn`

**Comment by mrmarktyy** [comment]
> 这是我手动删几个cookie才会跳转到的

请问是删了哪几个cookie呀？ 代码里没有看到删cookie的操作

**Comment by xfgryujk** [comment]
就是说你不用管`https://passport.weibo.com/visitor/visitor`这个页面了

**Comment by mrmarktyy** [comment]
感谢，我再试试
